const { signal, throwResponse } = require('../http');
const { stubImage } = require('../../media/stub-media');
const { providerRequestId, providerResult } = require('../result');

function createImageProviders(config, textProviders, getCancellation, usageTracker) {
  async function openai(prompt) {
    if (!config.env.OPENAI_API_KEY) throw new Error('OPENAI_API_KEY missing');
    const size = config.env.OPENAI_IMAGE_SIZE || '1024x1024'; const quality = config.env.OPENAI_IMAGE_QUALITY || 'medium';
    const response = await fetch('https://api.openai.com/v1/images/generations', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${config.env.OPENAI_API_KEY}` }, body: JSON.stringify({ model: config.env.OPENAI_IMAGE_MODEL || 'gpt-image-1', prompt, size, quality }), signal: signal(config.env.IMAGE_PROVIDER_TIMEOUT_MS || 180_000, getCancellation) });
    if (!response.ok) await throwResponse('openai', response); const data = await response.json(); if (!data.data?.[0]?.b64_json) throw new Error('OpenAI image error: no image returned'); const rawUsage = data.usage || null; return providerResult({ output: { buffer: Buffer.from(data.data[0].b64_json, 'base64'), mimeType: 'image/png', extension: 'png' }, provider: 'openai', model: config.env.OPENAI_IMAGE_MODEL || 'gpt-image-1', providerRequestId: providerRequestId(response, data), usage: { images: 1, size, quality, ...(rawUsage ? { inputTokens: rawUsage.input_tokens || 0, inputTextTokens: rawUsage.input_tokens_details?.text_tokens || 0, inputImageTokens: rawUsage.input_tokens_details?.image_tokens || 0, outputTokens: rawUsage.output_tokens || 0, outputImageTokens: rawUsage.output_tokens_details?.image_tokens || rawUsage.output_tokens || 0, totalTokens: rawUsage.total_tokens || 0, serviceTier: 'standard' } : {}) }, rawUsage, measurementStatus: rawUsage ? 'observed' : 'estimated' });
  }
  async function dezgo(prompt) {
    if (!config.env.DEZGO_API_KEY) throw new Error('DEZGO_API_KEY missing');
    const body = new URLSearchParams({ prompt, width: '1024', height: '1024', guidance: config.env.DEZGO_GUIDANCE || '7', steps: config.env.DEZGO_STEPS || '25', sampler: config.env.DEZGO_SAMPLER || 'euler_a', negative_prompt: 'blurry, unreadable, overly detailed, deformed' });
    const response = await fetch('https://api.dezgo.com/text2image', { method: 'POST', headers: { 'X-Dezgo-Key': config.env.DEZGO_API_KEY, Accept: 'image/png', 'Content-Type': 'application/x-www-form-urlencoded' }, body, signal: signal(config.env.IMAGE_PROVIDER_TIMEOUT_MS || 180_000, getCancellation) });
    if (!response.ok) await throwResponse('dezgo', response); return providerResult({ output: { buffer: Buffer.from(await response.arrayBuffer()), mimeType: 'image/png', extension: 'png' }, provider: 'dezgo', model: config.env.DEZGO_MODEL || 'text2image', providerRequestId: providerRequestId(response), usage: { images: 1, width: 1024, height: 1024, steps: Number(config.env.DEZGO_STEPS || 25), guidance: Number(config.env.DEZGO_GUIDANCE || 7), sampler: config.env.DEZGO_SAMPLER || 'euler_a' }, rawUsage: { inputSeed: response.headers.get('x-input-seed') || null }, measurementStatus: 'estimated' });
  }
  async function gemini(prompt, references) {
    if (!config.env.GEMINI_API_KEY) throw new Error('GEMINI_API_KEY missing'); const model = config.env.GEMINI_IMAGE_MODEL || 'gemini-3.1-flash-image';
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${config.env.GEMINI_API_KEY}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ contents: [{ parts: textProviders.geminiParts(prompt, references) }], generationConfig: { temperature: 0.7, responseModalities: ['TEXT','IMAGE'] } }), signal: signal(config.env.IMAGE_PROVIDER_TIMEOUT_MS || 180_000, getCancellation) });
    if (!response.ok) await throwResponse('gemini', response); const data = await response.json(); const part = (data.candidates?.[0]?.content?.parts || []).find((item) => item.inlineData?.data || item.inline_data?.data); const b64 = part?.inlineData?.data || part?.inline_data?.data; if (!b64) throw new Error('Gemini image error: no image returned'); const mimeType = part?.inlineData?.mimeType || part?.inline_data?.mime_type || 'image/png'; const rawUsage = data.usageMetadata || null; const outputImageTokens = (rawUsage?.candidatesTokensDetails || []).filter((item) => item.modality === 'IMAGE').reduce((sum, item) => sum + (item.tokenCount || 0), 0); const candidateTokens = rawUsage?.candidatesTokenCount || 0; return providerResult({ output: { buffer: Buffer.from(b64, 'base64'), mimeType, extension: mimeType === 'image/jpeg' ? 'jpg' : mimeType === 'image/webp' ? 'webp' : 'png' }, provider: 'gemini', model: data.modelVersion || model, providerRequestId: providerRequestId(response, data), usage: { images: 1, ...(rawUsage ? { inputTokens: rawUsage.promptTokenCount || 0, cachedInputTokens: rawUsage.cachedContentTokenCount || 0, outputTokens: candidateTokens + (rawUsage.thoughtsTokenCount || 0), candidateTokens, outputImageTokens, outputTextOrThinkingTokens: Math.max(0, candidateTokens - outputImageTokens) + (rawUsage.thoughtsTokenCount || 0), thinkingTokens: rawUsage.thoughtsTokenCount || 0, totalTokens: rawUsage.totalTokenCount || 0, serviceTier: rawUsage.serviceTier || 'standard' } : {}) }, rawUsage, measurementStatus: rawUsage ? 'observed' : 'estimated' });
  }
  function generate({ provider, prompt, references = [], title }) {
    const models = { stub: 'stub-image-v1', openai: config.env.OPENAI_IMAGE_MODEL || 'gpt-image-1', dezgo: config.env.DEZGO_MODEL || 'text2image', gemini: config.env.GEMINI_IMAGE_MODEL || 'gemini-3.1-flash-image' };
    const operation = () => provider === 'stub'
      ? Promise.resolve(providerResult({ output: { buffer: stubImage(prompt, title), mimeType: 'image/svg+xml', extension: 'svg' }, provider: 'stub', model: models.stub, usage: { images: 1 }, measurementStatus: 'not_applicable' }))
      : provider === 'openai' ? openai(prompt) : provider === 'dezgo' ? dezgo(prompt) : gemini(prompt, references);
    return usageTracker ? usageTracker.execute({ modality: 'image', provider, model: models[provider], inputMetadata: { promptCharacters: String(prompt).length, referenceCount: references.length } }, operation) : operation();
  }
  return { generate };
}
module.exports = { createImageProviders };
