const test=require('node:test');const assert=require('node:assert/strict');
const {createShotPlanningService}=require('../src/services/shot-planning.service');

test('shot planning falls back to deterministic chunked shots in stub mode, with no scene-count input anywhere',async()=>{const service=createShotPlanningService({textProviders:{}});const result=await service.plan({scriptText:'John stares at a wall for hours. Nothing moves. He finally blinks.',provider:'stub'});assert.equal(result.usedFallback,true);assert.ok(result.scenes.length>=1);assert.equal(result.narrationText.length>0,true);for(const scene of result.scenes){assert.equal(scene.narrationText.length>0,true);assert.equal(typeof scene.beat,'string');assert.equal(typeof scene.prompt,'string');}});

test('narration is finalized before any shot planning call, and shot planning receives only the finished narration, never the raw script',async()=>{const calls=[];const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{calls.push(request);if(request.includes('narrationText')&&!request.includes('shots')){return JSON.stringify({narrationText:'Mara opens the door slowly. She freezes. Blood covers the floor.'});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'Discovery',intent:'dread'}]});}return JSON.stringify({shots:[{narrationText:'Mara opens the door slowly. She freezes. Blood covers the floor.',visualPrompt:'Mara stands frozen in a doorway, blood visible on the floor beyond her.',actionPrompt:'Mara freezes at the doorway.'}]});}}});const result=await service.plan({scriptText:'INT. HOUSE - NIGHT\\nMara opens the door.',provider:'gemini',fallbackPolicy:'fail'});assert.equal(result.narrationText,'Mara opens the door slowly. She freezes. Blood covers the floor.');assert.equal(result.scenes.length,1);assert.equal(result.scenes[0].narrationText,'Mara opens the door slowly. She freezes. Blood covers the floor.');assert.equal(result.scenes[0].scriptFragment,result.scenes[0].narrationText);assert.equal(result.scenes[0].beat,'Mara freezes at the doorway.');assert.match(result.scenes[0].prompt,/doorway/);const shotCall=calls.find((request)=>request.includes('"shots"'));assert.doesNotMatch(shotCall,/INT\. HOUSE/);assert.match(shotCall,/Mara opens the door slowly/);});

test('final shot count is simply the concatenated length the AI actually returned, not a guessed or reconciled count',async()=>{const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{if(request.includes('narrationText')&&!request.includes('shots')){return JSON.stringify({narrationText:'A calm morning passes. Then five things happen fast: a door slams, a dog barks, a phone rings, a car screeches, and a light goes out.'});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'Calm then chaos',intent:'tension spike'}]});}return JSON.stringify({shots:[{narrationText:'A calm morning passes.',visualPrompt:'A quiet sunlit room at dawn, still and undisturbed.',actionPrompt:'Morning light fills the room.'},{narrationText:'Then five things happen fast: a door slams, a dog barks, a phone rings, a car screeches, and a light goes out.',visualPrompt:'A chaotic blur of a slamming door, a barking dog, and a ringing phone.',actionPrompt:'Chaos erupts all at once.'}]});}}});const result=await service.plan({scriptText:'A calm morning. Then chaos.',provider:'gemini',fallbackPolicy:'fail'});assert.equal(result.scenes.length,2);assert.equal(result.scenes[0].sceneNumber,1);assert.equal(result.scenes[1].sceneNumber,2);});

test('shot planning chunks a long narration into multiple calls rather than one unbounded call',async()=>{let narrationCalls=0;let shotCalls=0;const longNarration=Array.from({length:30},(_,i)=>`Sentence number ${i+1} describes a small distinct action happening in the story right now.`).join(' ');const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{if(request.includes('"narrationText"')&&!request.includes('shots')){narrationCalls+=1;return JSON.stringify({narrationText:longNarration});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'One long sequence',intent:''}]});}shotCalls+=1;return JSON.stringify({shots:[{narrationText:'Sentence number 1 describes a small distinct action happening in the story right now.',visualPrompt:'A clear depiction of the described action, subject and setting visible.',actionPrompt:'Subject performs the described action.'}]});}}});const result=await service.plan({scriptText:'source script text',provider:'gemini',fallbackPolicy:'fail'});assert.ok(shotCalls>1,`expected multiple shot-planning calls for a long narration, got ${shotCalls}`);assert.equal(result.scenes.length,shotCalls);});

test('shot planning falls back to deterministic shots for one chunk on provider failure without failing the whole plan',async()=>{let call=0;const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{if(request.includes('"narrationText"')&&!request.includes('shots')){return JSON.stringify({narrationText:'Real narration text for the scene.'});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'A',intent:''}]});}call+=1;throw new Error('provider unavailable');}}});const result=await service.plan({scriptText:'source',provider:'gemini',fallbackPolicy:'local'});assert.equal(result.usedFallback,true);assert.ok(result.scenes.length>=1);assert.match(result.scenes[0].narrationText,/Real narration/);assert.match(result.warning,/local fallback shots/);});

test('shot planning propagates a provider failure when fallbackPolicy is fail',async()=>{const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{if(request.includes('"narrationText"')&&!request.includes('shots')){return JSON.stringify({narrationText:'Real narration text.'});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'A',intent:''}]});}throw new Error('provider unavailable');}}});await assert.rejects(()=>service.plan({scriptText:'source',provider:'gemini',fallbackPolicy:'fail'}));});
