const test=require('node:test');const assert=require('node:assert/strict');
const {createShotPlanningService}=require('../src/services/shot-planning.service');

test('shot planning falls back to deterministic chunked shots in stub mode, with no scene-count input anywhere',async()=>{const service=createShotPlanningService({textProviders:{}});const result=await service.plan({scriptText:'John stares at a wall for hours. Nothing moves. He finally blinks.',provider:'stub'});assert.equal(result.usedFallback,true);assert.ok(result.scenes.length>=1);assert.equal(result.narrationText.length>0,true);for(const scene of result.scenes){assert.equal(scene.narrationText.length>0,true);assert.equal(typeof scene.beat,'string');assert.equal(typeof scene.prompt,'string');}});

test('narration is finalized before any shot planning call, and shot planning receives only the finished narration, never the raw script',async()=>{const calls=[];const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{calls.push(request);if(request.includes('narrationText')&&!request.includes('shots')){return JSON.stringify({narrationText:'Mara opens the door slowly. She freezes. Blood covers the floor.'});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'Discovery',intent:'dread'}]});}return JSON.stringify({shots:[{narrationText:'Mara opens the door slowly. She freezes. Blood covers the floor.',visualPrompt:'Mara stands frozen in a doorway, blood visible on the floor beyond her.',actionPrompt:'Mara freezes at the doorway.'}]});}}});const result=await service.plan({scriptText:'INT. HOUSE - NIGHT\\nMara opens the door.',provider:'gemini',fallbackPolicy:'fail'});assert.equal(result.narrationText,'Mara opens the door slowly. She freezes. Blood covers the floor.');assert.equal(result.scenes.length,1);assert.equal(result.scenes[0].narrationText,'Mara opens the door slowly. She freezes. Blood covers the floor.');assert.equal(result.scenes[0].scriptFragment,result.scenes[0].narrationText);assert.equal(result.scenes[0].beat,'Mara freezes at the doorway.');assert.match(result.scenes[0].prompt,/doorway/);const shotCall=calls.find((request)=>request.includes('"shots"'));assert.doesNotMatch(shotCall,/INT\. HOUSE/);assert.match(shotCall,/Mara opens the door slowly/);});

test('final shot count is simply the concatenated length the AI actually returned, not a guessed or reconciled count',async()=>{const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{if(request.includes('narrationText')&&!request.includes('shots')){return JSON.stringify({narrationText:'A calm morning passes. Then five things happen fast: a door slams, a dog barks, a phone rings, a car screeches, and a light goes out.'});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'Calm then chaos',intent:'tension spike'}]});}return JSON.stringify({shots:[{narrationText:'A calm morning passes.',visualPrompt:'A quiet sunlit room at dawn, still and undisturbed.',actionPrompt:'Morning light fills the room.'},{narrationText:'Then five things happen fast: a door slams, a dog barks, a phone rings, a car screeches, and a light goes out.',visualPrompt:'A chaotic blur of a slamming door, a barking dog, and a ringing phone.',actionPrompt:'Chaos erupts all at once.'}]});}}});const result=await service.plan({scriptText:'A calm morning. Then chaos.',provider:'gemini',fallbackPolicy:'fail'});assert.equal(result.scenes.length,2);assert.equal(result.scenes[0].sceneNumber,1);assert.equal(result.scenes[1].sceneNumber,2);});

test('shot planning chunks a long narration into multiple calls rather than one unbounded call',async()=>{let narrationCalls=0;let shotCalls=0;const longNarration=Array.from({length:30},(_,i)=>`Sentence number ${i+1} describes a small distinct action happening in the story right now.`).join(' ');const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{if(request.includes('"narrationText"')&&!request.includes('shots')){narrationCalls+=1;return JSON.stringify({narrationText:longNarration});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'One long sequence',intent:''}]});}shotCalls+=1;return JSON.stringify({shots:[{narrationText:'Sentence number 1 describes a small distinct action happening in the story right now.',visualPrompt:'A clear depiction of the described action, subject and setting visible.',actionPrompt:'Subject performs the described action.'}]});}}});const result=await service.plan({scriptText:'source script text',provider:'gemini',fallbackPolicy:'fail'});assert.ok(shotCalls>1,`expected multiple shot-planning calls for a long narration, got ${shotCalls}`);assert.equal(result.scenes.length,shotCalls);});

test('shot planning falls back to deterministic shots for one chunk on provider failure without failing the whole plan',async()=>{let call=0;const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{if(request.includes('"narrationText"')&&!request.includes('shots')){return JSON.stringify({narrationText:'Real narration text for the scene.'});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'A',intent:''}]});}call+=1;throw new Error('provider unavailable');}}});const result=await service.plan({scriptText:'source',provider:'gemini',fallbackPolicy:'local'});assert.equal(result.usedFallback,true);assert.ok(result.scenes.length>=1);assert.match(result.scenes[0].narrationText,/Real narration/);assert.match(result.warning,/local fallback shots/);});

test('shot planning propagates a provider failure when fallbackPolicy is fail',async()=>{const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{if(request.includes('"narrationText"')&&!request.includes('shots')){return JSON.stringify({narrationText:'Real narration text.'});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'A',intent:''}]});}throw new Error('provider unavailable');}}});await assert.rejects(()=>service.plan({scriptText:'source',provider:'gemini',fallbackPolicy:'fail'}));});

test('maxShots is passed to the model as an overall ceiling plus a soft per-chunk budget, not omitted or silently enforced only after the fact',async()=>{let shotRequest;const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{if(request.includes('"narrationText"')&&!request.includes('shots')){return JSON.stringify({narrationText:'A short scene with one clear beat.'});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'A',intent:''}]});}shotRequest=request;return JSON.stringify({shots:[{narrationText:'A short scene with one clear beat.',visualPrompt:'A clear depiction of the beat, subject and setting visible.',actionPrompt:'Subject completes the beat.'}]});}}});await service.plan({scriptText:'source',provider:'gemini',fallbackPolicy:'fail',maxShots:40});assert.match(shotRequest,/maximum of 40 shots/);assert.match(shotRequest,/approximate share of that budget/);assert.match(shotRequest,/soft target, not a hard rule/);});

test('maxShots omitted leaves the shot-planning request free of any cap or budget language',async()=>{let shotRequest;const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{if(request.includes('"narrationText"')&&!request.includes('shots')){return JSON.stringify({narrationText:'A short scene.'});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'A',intent:''}]});}shotRequest=request;return JSON.stringify({shots:[{narrationText:'A short scene.',visualPrompt:'A clear depiction, subject and setting visible.',actionPrompt:'Subject acts.'}]});}}});await service.plan({scriptText:'source',provider:'gemini',fallbackPolicy:'fail'});assert.doesNotMatch(shotRequest,/SHOT BUDGET/);assert.doesNotMatch(shotRequest,/shot cap/);});

test('maxShots is a ceiling, not a target: the AI landing under the cap is used exactly as returned, no padding or trimming',async()=>{const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{if(request.includes('"narrationText"')&&!request.includes('shots')){return JSON.stringify({narrationText:'A calm scene with three small beats in it today.'});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'A',intent:''}]});}return JSON.stringify({shots:[{narrationText:'A calm scene',visualPrompt:'A calm room, clearly lit, subject visible.',actionPrompt:'Subject rests calmly.'},{narrationText:'with three small beats in it today.',visualPrompt:'A close detail shot of the same room, later.',actionPrompt:'Subject notices something small.'}]});}}});const result=await service.plan({scriptText:'source',provider:'gemini',fallbackPolicy:'fail',maxShots:40});assert.equal(result.scenes.length,2);assert.equal(result.warning,'');});

test('maxShots slightly exceeded triggers a deterministic merge-down to exactly the cap, preserving all narration text and warning without failing the plan',async()=>{const shots=Array.from({length:5},(_,i)=>({narrationText:`Beat number ${i+1} happens here in the story.`,visualPrompt:`A clear depiction of beat ${i+1}, subject and setting visible.`,actionPrompt:`Subject performs beat ${i+1}.`}));const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{if(request.includes('"narrationText"')&&!request.includes('shots')){return JSON.stringify({narrationText:'Five short beats happen in sequence today.'});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'A',intent:''}]});}return JSON.stringify({shots});}}});const result=await service.plan({scriptText:'source',provider:'gemini',fallbackPolicy:'fail',maxShots:4});assert.equal(result.scenes.length,4);assert.match(result.warning,/slightly exceeded the 4-shot cap \(5 planned\)/);const allNarration=result.scenes.map((scene)=>scene.narrationText).join(' ');for(let i=1;i<=5;i+=1)assert.match(allNarration,new RegExp(`Beat number ${i} happens`));});

test('maxShots substantially exceeded still trims to exactly the cap but flags the budgeting mechanism distinctly',async()=>{const shots=Array.from({length:20},(_,i)=>({narrationText:`Beat number ${i+1} happens here in the story today.`,visualPrompt:`A clear depiction of beat ${i+1}, subject and setting visible.`,actionPrompt:`Subject performs beat ${i+1}.`}));const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{if(request.includes('"narrationText"')&&!request.includes('shots')){return JSON.stringify({narrationText:'Twenty short beats happen in sequence today.'});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'A',intent:''}]});}return JSON.stringify({shots});}}});const result=await service.plan({scriptText:'source',provider:'gemini',fallbackPolicy:'fail',maxShots:5});assert.equal(result.scenes.length,5);assert.match(result.warning,/substantially exceeded the 5-shot cap \(20 planned\)/);assert.match(result.warning,/budgeting undershot the mark/);});

test('maxShots merge-down keeps the survivor\'s visualPrompt/actionPrompt rather than inventing a blended one',async()=>{const shots=[{narrationText:'A tiny beat.',visualPrompt:'VISUAL_A',actionPrompt:'ACTION_A'},{narrationText:'A much longer and more detailed beat with far more narration content in it.',visualPrompt:'VISUAL_B',actionPrompt:'ACTION_B'}];const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{if(request.includes('"narrationText"')&&!request.includes('shots')){return JSON.stringify({narrationText:'A tiny beat. A much longer and more detailed beat with far more narration content in it.'});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'A',intent:''}]});}return JSON.stringify({shots});}}});const result=await service.plan({scriptText:'source',provider:'gemini',fallbackPolicy:'fail',maxShots:1});assert.equal(result.scenes.length,1);assert.equal(result.scenes[0].prompt,'VISUAL_B');assert.equal(result.scenes[0].beat,'ACTION_B');assert.match(result.scenes[0].narrationText,/A tiny beat/);assert.match(result.scenes[0].narrationText,/much longer and more detailed/);});

test('budgetTelemetry reports cap, produced, merged, and overshoot percent for an over-cap run',async()=>{const shots=Array.from({length:58},(_,i)=>({narrationText:`Beat number ${i+1} occurs.`,visualPrompt:`A clear depiction of beat ${i+1}.`,actionPrompt:`Subject performs beat ${i+1}.`}));const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{if(request.includes('"narrationText"')&&!request.includes('shots')){return JSON.stringify({narrationText:'Fifty eight short beats occur in sequence.'});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'A',intent:''}]});}return JSON.stringify({shots});}}});const result=await service.plan({scriptText:'source',provider:'gemini',fallbackPolicy:'fail',maxShots:50});assert.equal(result.scenes.length,50);assert.deepEqual(result.budgetTelemetry,{cap:50,produced:58,merged:8,overshootPercent:16,chunks:result.budgetTelemetry.chunks});assert.equal(result.budgetTelemetry.chunks.length,1);assert.equal(result.budgetTelemetry.chunks[0].returned,58);});

test('budgetTelemetry reports zero merged and non-positive overshoot when the AI already lands under the cap',async()=>{const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{if(request.includes('"narrationText"')&&!request.includes('shots')){return JSON.stringify({narrationText:'A calm scene with two small beats.'});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'A',intent:''}]});}return JSON.stringify({shots:[{narrationText:'A calm scene',visualPrompt:'A calm room, subject visible.',actionPrompt:'Subject rests.'},{narrationText:'with two small beats.',visualPrompt:'A close detail shot, later.',actionPrompt:'Subject notices something.'}]});}}});const result=await service.plan({scriptText:'source',provider:'gemini',fallbackPolicy:'fail',maxShots:40});assert.equal(result.budgetTelemetry.cap,40);assert.equal(result.budgetTelemetry.produced,2);assert.equal(result.budgetTelemetry.merged,0);assert.ok(result.budgetTelemetry.overshootPercent<=0);});

test('budgetTelemetry is absent entirely when no cap is set -- not present with null/zero values',async()=>{const service=createShotPlanningService({textProviders:{call:async(_p,request)=>{if(request.includes('"narrationText"')&&!request.includes('shots')){return JSON.stringify({narrationText:'A short scene.'});}if(request.includes('sequences')){return JSON.stringify({sequences:[{label:'A',intent:''}]});}return JSON.stringify({shots:[{narrationText:'A short scene.',visualPrompt:'A clear depiction, subject visible.',actionPrompt:'Subject acts.'}]});}}});const result=await service.plan({scriptText:'source',provider:'gemini',fallbackPolicy:'fail'});assert.equal('budgetTelemetry' in result,false);});

test('prepareNarration preserves original source separately and returns text-only canonical scene boundaries',async()=>{const service=createShotPlanningService({textProviders:{call:async(_provider,request)=>{if(request.includes('continuous spoken narration'))return JSON.stringify({narrationText:'Mara opens the door. She freezes.'});if(request.includes('"segments"'))return JSON.stringify({segments:[{narrationText:'Mara opens the door.'},{narrationText:'She freezes.'}]});throw new Error(`unexpected request: ${request}`);}}});const result=await service.prepareNarration({scriptText:'INT. HOUSE - NIGHT\\nMara opens the door and freezes.',provider:'gemini',fallbackPolicy:'fail'});assert.equal(result.scenes.length,2);assert.match(result.scenes[0].sourceScriptFragment,/INT\. HOUSE/);assert.equal(result.scenes[0].scriptFragment,result.scenes[0].sourceScriptFragment);assert.equal(result.scenes[0].narrationText,'Mara opens the door.');assert.equal(result.scenes[0].prompt,'');assert.equal(result.scenes[0].beat,'');});

test('planVisuals adds visual fields without rewriting scene identity, source, narration, or boundaries',async()=>{const service=createShotPlanningService({textProviders:{call:async()=>JSON.stringify({visuals:[{sceneNumber:1,visualPrompt:'Mara stands in the doorway, one hand on the knob.',actionPrompt:'Mara opens the door.'},{sceneNumber:2,visualPrompt:'Mara freezes in the dark hall.',actionPrompt:'Mara freezes.'}]})}});const scenes=[{id:'a',title:'Scene 1',sourceScriptFragment:'SOURCE A',scriptFragment:'SOURCE A',narrationText:'Mara opens the door.',structuralContextStale:true},{id:'b',title:'Scene 2',sourceScriptFragment:'SOURCE B',scriptFragment:'SOURCE B',narrationText:'She freezes.'}];const result=await service.planVisuals({scenes,provider:'gemini',style:{id:'basic',promptText:'simple'},fallbackPolicy:'fail'});assert.deepEqual(result.scenes.map(({id,sourceScriptFragment,narrationText})=>({id,sourceScriptFragment,narrationText})),scenes.map(({id,sourceScriptFragment,narrationText})=>({id,sourceScriptFragment,narrationText})));assert.match(result.scenes[0].prompt,/doorway/);assert.equal(result.scenes[1].promptGeneratedFromNarration,'She freezes.');assert.equal(result.scenes[0].structuralContextStale,false);});

test('prepareNarration records exact source offsets when segmentation returns aligned source excerpts',async()=>{const script='INT. HOUSE - NIGHT\nMara opens the door. She freezes.';const service=createShotPlanningService({textProviders:{call:async(_provider,request)=>{if(request.includes('continuous spoken narration'))return JSON.stringify({narrationText:'Mara opens the door. She freezes.'});if(request.includes('"segments"'))return JSON.stringify({segments:[{sourceScriptFragment:'INT. HOUSE - NIGHT\nMara opens the door.',narrationText:'Mara opens the door.'},{sourceScriptFragment:'She freezes.',narrationText:'She freezes.'}]});throw new Error(`unexpected request: ${request}`);}}});const result=await service.prepareNarration({scriptText:script,provider:'gemini',fallbackPolicy:'fail'});assert.equal(result.scenes.length,2);assert.equal(result.scenes[0].sourceMappingMethod,'model');assert.equal(result.scenes[0].sourceStart,0);assert.equal(result.scenes[1].sourceEnd,script.length);assert.ok(result.scenes[0].sourceEnd<=result.scenes[1].sourceStart);});

test('planVisuals rejects duplicate or incomplete provider scene mappings when fallback is disabled',async()=>{const service=createShotPlanningService({textProviders:{call:async()=>JSON.stringify({visuals:[{sceneNumber:1,visualPrompt:'One complete visual.',actionPrompt:'Subject acts.'},{sceneNumber:1,visualPrompt:'Duplicate visual.',actionPrompt:'Subject reacts.'}]})}});const scenes=[{id:'a',narrationText:'One.'},{id:'b',narrationText:'Two.'}];await assert.rejects(()=>service.planVisuals({scenes,provider:'gemini',fallbackPolicy:'fail'}),/exactly one complete/);});

test('planVisuals marks fallback per batch instead of contaminating later successful batches',async()=>{let call=0;const scenes=Array.from({length:13},(_,index)=>({id:`s${index+1}`,narrationText:`Narration ${index+1}.`}));const service=createShotPlanningService({textProviders:{call:async()=>{call+=1;if(call===1)return JSON.stringify({visuals:[{sceneNumber:1,visualPrompt:'Incomplete.',actionPrompt:'Acts.'}]});return JSON.stringify({visuals:[{sceneNumber:1,visualPrompt:'A complete final scene visual.',actionPrompt:'Subject finishes.'}]});}}});const result=await service.planVisuals({scenes,provider:'gemini',fallbackPolicy:'local'});assert.equal(result.scenes[0].promptIsFallback,true);assert.equal(result.scenes[11].promptIsFallback,true);assert.equal(result.scenes[12].promptIsFallback,false);});

test('prepareNarration uses the editable style prompt while retaining the source-of-truth guard',async()=>{let narrationRequest='';const service=createShotPlanningService({textProviders:{call:async(_provider,request)=>{if(request.includes('continuous spoken narration')){narrationRequest=request;return JSON.stringify({narrationText:'Mara enters.'});}return JSON.stringify({segments:[{sourceScriptFragment:'Mara enters.',narrationText:'Mara enters.'}]});}}});await service.prepareNarration({scriptText:'Mara enters.',provider:'gemini',fallbackPolicy:'fail',narrationPromptText:'Use spare, rhythmic sentences.'});assert.match(narrationRequest,/Use spare, rhythmic sentences\./);assert.match(narrationRequest,/source text below is the only authority/i);assert.doesNotMatch(narrationRequest,/Stay close to the source text/);});
