const fs = require('node:fs');
const { spawn } = require('node:child_process');
const text2wav = require('text2wav');
const { buildWavBuffer, concatenatePcmLines, parseWavPcm } = require('../../media/wav');
const { signal, throwResponse } = require('../http');

function hash(value){let h=0;for(const ch of String(value))h=(h*31+ch.charCodeAt(0))>>>0;return h;}
const PIPER_SAMPLE_RATE=22050; // native rate of Piper's "medium" quality voices (lessac/amy/ryan-medium); revisit if a "low" (16000Hz) or other-tier voice is added
function createAudioProviders(config,getCancellation){
  async function stub(lines){const variants=['en','en+f3','en+m3','en+f4','en+m4','en+f2'];const pcm=[];for(const line of lines)pcm.push(await text2wav(line.text,{voice:variants[hash(line.speaker)%variants.length],speed:145,pitch:48,amplitude:100}));return{buffer:buildWavBuffer(concatenatePcmLines(pcm)),mimeType:'audio/wav',extension:'wav'};}
  function piperLine(text,voice){return new Promise((resolve,reject)=>{const model=`${config.paths.piperVoices}/${voice}.onnx`;if(!fs.existsSync(config.paths.piper)||!fs.existsSync(model))return reject(new Error('Piper is not installed. Run npm run setup:piper.'));const chunks=[];const child=spawn(config.paths.piper,['--model',model,'--output-raw'],{stdio:['pipe','pipe','pipe']});let stderr='';child.stdout.on('data',(x)=>chunks.push(x));child.stderr.on('data',(x)=>stderr+=x);child.on('error',reject);child.on('close',(code)=>code===0?resolve(Buffer.concat(chunks)):reject(new Error(`Piper failed (${code}): ${stderr.trim()}`)));child.stdin.end(text);});}
  async function piper(lines){const pcm=[];for(const line of lines)pcm.push(await piperLine(line.text,config.piperVoices[hash(line.speaker)%config.piperVoices.length]));const opts={sampleRate:PIPER_SAMPLE_RATE};return{buffer:buildWavBuffer(concatenatePcmLines(pcm,opts),opts),mimeType:'audio/wav',extension:'wav'};}
  async function elevenLine(text,voiceId){if(!config.env.ELEVENLABS_API_KEY)throw new Error('ELEVENLABS_API_KEY missing');const format=config.env.ELEVENLABS_OUTPUT_FORMAT||'pcm_24000';const response=await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${encodeURIComponent(voiceId)}?output_format=${encodeURIComponent(format)}`,{method:'POST',headers:{'Content-Type':'application/json','xi-api-key':config.env.ELEVENLABS_API_KEY},body:JSON.stringify({text,model_id:config.env.ELEVENLABS_MODEL_ID||'eleven_turbo_v2_5'}),signal:signal(config.env.AUDIO_PROVIDER_TIMEOUT_MS||60000,getCancellation)});if(!response.ok)await throwResponse('elevenlabs',response);return Buffer.from(await response.arrayBuffer());}
  async function elevenlabs(lines,map){const pcm=[];for(const line of lines){const voice=map?.[line.speaker]||map?.Narrator;if(!voice?.voiceId)throw new Error(`No ElevenLabs voice mapped for speaker "${line.speaker}"`);pcm.push(await elevenLine(line.text,voice.voiceId));}return{buffer:buildWavBuffer(concatenatePcmLines(pcm)),mimeType:'audio/wav',extension:'wav'};}
  async function sparkLine(text,voiceId){const headers={'Content-Type':'application/json'};if(config.sparkServiceToken)headers.Authorization=`Bearer ${config.sparkServiceToken}`;const response=await fetch(`${config.sparkUrl}/synthesize`,{method:'POST',headers,body:JSON.stringify({text,voiceId}),signal:signal(config.sparkTimeout,getCancellation)});if(!response.ok){const detail=await response.json().catch(()=>({}));throw new Error(detail.detail||`Voice cloning service error (${response.status})`);}return Buffer.from(await response.arrayBuffer());}
  async function spark(lines,map){const parsed=[];for(const line of lines){const voice=map?.[line.speaker]||map?.Narrator;if(!voice?.voiceId)throw new Error(`No cloned voice assigned for speaker "${line.speaker}"`);parsed.push(parseWavPcm(await sparkLine(line.text,voice.voiceId)));}const {sampleRate,channels,bitsPerSample}=parsed[0];return{buffer:buildWavBuffer(concatenatePcmLines(parsed.map(x=>x.pcm),{sampleRate,channels,bitsPerSample}),{sampleRate,channels,bitsPerSample}),mimeType:'audio/wav',extension:'wav'};}
  return{generate:({provider,lines,voiceMap={}})=>provider==='stub'?stub(lines):provider==='piper'?piper(lines):provider==='spark'?spark(lines,voiceMap):elevenlabs(lines,voiceMap)};
}
module.exports={createAudioProviders};
